### Numpy install

In [2]:
!pip install numpy

  Using cached numpy-2.2.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Using cached numpy-2.2.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.1 MB)


In [2]:
import numpy as np

### Type

In [4]:
type(1)

int

In [5]:
bool
int, float, complex
str 
list, tuple, range
set
dict

dict

In [7]:
np.dtype(np.True_)

dtype('bool')

In [ ]:
np.bool
np.int8, np.int16, np.int32, np.int64
np.uint8, np.uint16, np.uint32, np.uint64

np.float16, np.float32, np.float64

np.str_, np.bytes_

np.ndarray

### Array

In [13]:
list_ = list([1, 2, 3])
# array is warper of ndarray (?)
array = np.array([1, 2, 3])
type(array)

numpy.ndarray

In [19]:
scaler = np.array(1)
scaler.shape

()

In [15]:
array = np.array([1, 2, 3])
array.ndim
array.shape

(3,)

In [35]:
table = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)
table

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
matrix = np.array(
    [
        [
            [1, 2, 4, 5],
            [2, 3, 6, 7],
            [2, 29, 6, 32]
        ],
        [
            [1, 2, 7, 86],
            [2, 6, 6, 7],
            [2, 5, 6, 3]
        ]
    ]
)
matrix.shape
matrix.ndim

3

### Array Attributes

In [38]:
table = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)
table.ndim

2

In [39]:
table.shape

(2, 3)

In [40]:
table.dtype

dtype('int64')

In [43]:
table.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
table.size

6

In [45]:
table.itemsize

8

In [47]:
table.itemsize * table.size
table.nbytes

48

### function (I)

In [79]:
table = np.array(
    [
        [1, 2, 3, 4],
        [4, 0, 6, 6],
        [7, 8, 9, 1]
    ]
)

In [81]:
table

array([[1, 2, 3, 4],
       [4, 0, 6, 6],
       [7, 8, 9, 1]])

In [84]:
table.ndim

2

In [83]:
table.shape

(3, 4)

In [85]:
table.mean()

np.float64(4.25)

In [86]:
table.mean(axis=0)

array([4.        , 3.33333333, 6.        , 3.66666667])

In [88]:
table.mean(axis=0).ndim

1

In [87]:
table.mean(axis=0).shape

(4,)

In [89]:
table.mean(axis=1)

array([2.5 , 4.  , 6.25])

In [90]:
table.mean(axis=1).ndim

1

In [91]:
table.mean(axis=1).shape

(3,)

In [76]:
table.mean()
table.min()
table.max()
table.var()
table.argmin() # ?
table.argmax() # ?
table.all()
table.any()

np.True_

In [92]:
table.mean(axis=1) # axis ?

array([2.5 , 4.  , 6.25])

### functions (II)

In [93]:
table = np.array(
    [
        [1, 2, 3, 4],
        [4, 0, 6, 6],
        [7, 8, 9, 1]
    ]
)

In [95]:
table.shape

(3, 4)

In [98]:
table.reshape(2, 6)

array([[1, 2, 3, 4, 4, 0],
       [6, 6, 7, 8, 9, 1]])

In [99]:
table.reshape(4, 3)

array([[1, 2, 3],
       [4, 4, 0],
       [6, 6, 7],
       [8, 9, 1]])