### Numpy install

In [2]:
!pip install numpy

  Using cached numpy-2.2.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (62 kB)
Using cached numpy-2.2.5-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.1 MB)


In [2]:
import numpy as np

### Type

In [4]:
type(1)

int

In [5]:
bool
int, float, complex
str 
list, tuple, range
set
dict

dict

In [7]:
np.dtype(np.True_)

dtype('bool')

In [ ]:
np.bool
np.int8, np.int16, np.int32, np.int64
np.uint8, np.uint16, np.uint32, np.uint64

np.float16, np.float32, np.float64

np.str_, np.bytes_

np.ndarray

### Array

In [13]:
list_ = list([1, 2, 3])
# array is warper of ndarray (?)
array = np.array([1, 2, 3])
type(array)

numpy.ndarray

In [19]:
scaler = np.array(1)
scaler.shape

()

In [15]:
array = np.array([1, 2, 3])
array.ndim
array.shape

(3,)

In [35]:
table = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)
table

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
matrix = np.array(
    [
        [
            [1, 2, 4, 5],
            [2, 3, 6, 7],
            [2, 29, 6, 32]
        ],
        [
            [1, 2, 7, 86],
            [2, 6, 6, 7],
            [2, 5, 6, 3]
        ]
    ]
)
matrix.shape
matrix.ndim

3

### Array Attributes

In [38]:
table = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)
table.ndim

2

In [39]:
table.shape

(2, 3)

In [40]:
table.dtype

dtype('int64')

In [43]:
table.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [44]:
table.size

6

In [45]:
table.itemsize

8

In [47]:
table.itemsize * table.size
table.nbytes

48

### function (I)

In [79]:
table = np.array(
    [
        [1, 2, 3, 4],
        [4, 0, 6, 6],
        [7, 8, 9, 1]
    ]
)

In [81]:
table

array([[1, 2, 3, 4],
       [4, 0, 6, 6],
       [7, 8, 9, 1]])

In [84]:
table.ndim

2

In [83]:
table.shape

(3, 4)

In [85]:
table.mean()

np.float64(4.25)

In [86]:
table.mean(axis=0)

array([4.        , 3.33333333, 6.        , 3.66666667])

In [88]:
table.mean(axis=0).ndim

1

In [87]:
table.mean(axis=0).shape

(4,)

In [89]:
table.mean(axis=1)

array([2.5 , 4.  , 6.25])

In [90]:
table.mean(axis=1).ndim

1

In [91]:
table.mean(axis=1).shape

(3,)

In [76]:
table.mean()
table.min()
table.max()
table.var()
table.argmin() # ?
table.argmax() # ?
table.all()
table.any()

np.True_

In [92]:
table.mean(axis=1) # axis ?

array([2.5 , 4.  , 6.25])

### functions (II)

In [93]:
table = np.array(
    [
        [1, 2, 3, 4],
        [4, 0, 6, 6],
        [7, 8, 9, 1]
    ]
)

In [95]:
table.shape

(3, 4)

In [110]:
table.reshape(2, 2, 1, 3)

array([[[[1., 2., 3.]],

        [[4., 4., 0.]]],


       [[[6., 6., 7.]],

        [[8., 9., 1.]]]])

In [99]:
table.reshape(4, 3)

array([[1, 2, 3],
       [4, 4, 0],
       [6, 6, 7],
       [8, 9, 1]])

In [100]:
table.dtype

dtype('int64')

In [102]:
table = table.astype(np.float64)

In [103]:
table

array([[1., 2., 3., 4.],
       [4., 0., 6., 6.],
       [7., 8., 9., 1.]])

In [106]:
table.tolist()

[[1.0, 2.0, 3.0, 4.0], [4.0, 0.0, 6.0, 6.0], [7.0, 8.0, 9.0, 1.0]]

In [113]:
help(np.clip)

Help on _ArrayFunctionDispatcher in module numpy:

clip(a, a_min=<no value>, a_max=<no value>, out=None, *, min=<no value>, max=<no value>, **kwargs)
    Clip (limit) the values in an array.

    Given an interval, values outside the interval are clipped to
    the interval edges.  For example, if an interval of ``[0, 1]``
    is specified, values smaller than 0 become 0, and values larger
    than 1 become 1.

    Equivalent to but faster than ``np.minimum(a_max, np.maximum(a, a_min))``.

    No check is performed to ensure ``a_min < a_max``.

    Parameters
    ----------
    a : array_like
        Array containing elements to clip.
    a_min, a_max : array_like or None
        Minimum and maximum value. If ``None``, clipping is not performed on
        the corresponding edge. If both ``a_min`` and ``a_max`` are ``None``,
        the elements of the returned array stay the same. Both are broadcasted
        against ``a``.
    out : ndarray, optional
        The results will be placed

In [112]:
np.clip?

Signature:      
np.clip(
    a,
    a_min=<no value>,
    a_max=<no value>,
    out=None,
    *,
    min=<no value>,
    max=<no value>,
    **kwargs,
)
Call signature:  np.clip(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function clip at 0x7804a00ddee0>
File:            ~/python-projects/000-quera-bc/venv/lib/python3.12/site-packages/numpy/_core/fromnumeric.py
Docstring:      
Clip (limit) the values in an array.

Given an interval, values outside the interval are clipped to
the interval edges.  For example, if an interval of ``[0, 1]``
is specified, values smaller than 0 become 0, and values larger
than 1 become 1.

Equivalent to but faster than ``np.minimum(a_max, np.maximum(a, a_min))``.

No check is performed to ensure ``a_min < a_max``.

Parameters
----------
a : array_like
    Array containing elements to clip.
a_min, a_max : array_like or None
    Minimum and maximum value. If ``None``, clipping is not performed on
    the corresponding edge. I

In [108]:
table.clip(0, 5)

array([[1., 2., 3., 4.],
       [4., 0., 5., 5.],
       [5., 5., 5., 1.]])

In [120]:
table.shape

(3, 4)

In [118]:
table.reshape(12)

array([1., 2., 3., 4., 4., 0., 6., 6., 7., 8., 9., 1.])

In [125]:
table.repeat(3, axis=1)

array([[1., 1., 1., 2., 2., 2., 3., 3., 3., 4., 4., 4.],
       [4., 4., 4., 0., 0., 0., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 8., 8., 8., 9., 9., 9., 1., 1., 1.]])

In [132]:
matrix_1 = np.array(
    [
        [1, 2],
        [3, 4]
    ]
)
matrix

array([[1, 2],
       [3, 4]])

In [133]:
matrix_2 = np.array(
    [
        [4, 5],
        [7, 9]
    ]
)
matrix_2

array([[4, 5],
       [7, 9]])

In [135]:
matrix_1 * matrix_2

array([[ 4, 10],
       [21, 36]])

In [136]:
matrix_1 @ matrix_2

array([[18, 23],
       [40, 51]])

In [137]:
matrix_1.dot(matrix_2)

array([[18, 23],
       [40, 51]])

In [139]:
table

array([[1., 2., 3., 4.],
       [4., 0., 6., 6.],
       [7., 8., 9., 1.]])

In [146]:
table.reshape(2, -1, 2)

array([[[1., 2.],
        [3., 4.],
        [4., 0.]],

       [[6., 6.],
        [7., 8.],
        [9., 1.]]])

In [140]:
table.reshape(12)

array([1., 2., 3., 4., 4., 0., 6., 6., 7., 8., 9., 1.])

In [147]:
table.flatten()

array([1., 2., 3., 4., 4., 0., 6., 6., 7., 8., 9., 1.])

In [155]:
matrix = np.array(
    [
        [
            [1, 2, 4, 5],
            [2, 3, 6, 7],
            [2, 29, 6, 8]
        ],
        [
            [1, 2, 7, 1],
            [2, 6, 6, 7],
            [2, 5, 6, 3]
        ]
    ]
)
matrix.flatten()

array([ 1,  2,  4,  5,  2,  3,  6,  7,  2, 29,  6,  8,  1,  2,  7,  1,  2,
        6,  6,  7,  2,  5,  6,  3])

In [151]:
matrix.ravel()

array([ 1,  2,  4,  5,  2,  3,  6,  7,  2, 29,  6, 32,  1,  2,  7, 86,  2,
        6,  6,  7,  2,  5,  6,  3])

### flatten & ravel

In [174]:
matrix[0, 0, 0] = 10

In [163]:
m_flat_1 = matrix.flatten()
m_flat_2 = matrix.ravel()

In [175]:
m_flat_1

array([ 1,  2,  4,  5,  2,  3,  6,  7,  2, 29,  6,  8,  1,  2,  7,  1,  2,
        6,  6,  7,  2,  5,  6,  3])

In [180]:
m_flat_1[0] = 300

In [181]:
matrix

array([[[500,   2,   4,   5],
        [  2,   3,   6,   7],
        [  2,  29,   6,   8]],

       [[  1,   2,   7,   1],
        [  2,   6,   6,   7],
        [  2,   5,   6,   3]]])

In [178]:
m_flat_2[0] = 500

In [179]:
matrix

array([[[500,   2,   4,   5],
        [  2,   3,   6,   7],
        [  2,  29,   6,   8]],

       [[  1,   2,   7,   1],
        [  2,   6,   6,   7],
        [  2,   5,   6,   3]]])

### Copy & View

In [199]:
arr = np.array(
    [
        [4, 5],
        [7, 9]
    ]
)

t1 = arr # view .view()
t2 = arr.copy()

arr[0, 0] = 40

In [202]:
t1

array([[40,  5],
       [ 7,  9]])

In [203]:
t2

array([[4, 5],
       [7, 9]])

### functions (III)

In [207]:
a_array = np.array(
    [
        [4, 5],
        [7, 9]
    ]
)

In [209]:
np.linalg.det(a_array)

np.float64(0.9999999999999964)

In [208]:
np.linalg.inv(a_array)

array([[ 9., -5.],
       [-7.,  4.]])

In [215]:
help(np.linalg.norm)

Help on _ArrayFunctionDispatcher in module numpy.linalg:

norm(x, ord=None, axis=None, keepdims=False)
    Matrix or vector norm.

    This function is able to return one of eight different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.

    Parameters
    ----------
    x : array_like
        Input array.  If `axis` is None, `x` must be 1-D or 2-D, unless `ord`
        is None. If both `axis` and `ord` are None, the 2-norm of
        ``x.ravel`` will be returned.
    ord : {int, float, inf, -inf, 'fro', 'nuc'}, optional
        Order of the norm (see table under ``Notes`` for what values are
        supported for matrices and vectors respectively). inf means numpy's
        `inf` object. The default is None.
    axis : {None, int, 2-tuple of ints}, optional.
        If `axis` is an integer, it specifies the axis of `x` along which to
        compute the vector norms.  If `axis` is a 2-tuple, it spe

In [210]:
np.linalg.norm(a_array)

np.float64(13.076696830622021)

In [211]:
np.log(a_array)

array([[1.38629436, 1.60943791],
       [1.94591015, 2.19722458]])

In [212]:
np.exp(a_array)

array([[  54.59815003,  148.4131591 ],
       [1096.63315843, 8103.08392758]])

In [213]:
np.sqrt(a_array)

array([[2.        , 2.23606798],
       [2.64575131, 3.        ]])

### constants

In [223]:
array = np.array(
    [
        [np.nan, 1],
        [2, np.nan]
    ]
)

In [231]:
np.isnan(array)

array([[ True, False],
       [False,  True]])

In [226]:
array

array([[nan,  1.],
       [ 2., nan]])

In [221]:
type(np.nan)

float

In [222]:
arr.dtype

dtype('int64')

In [227]:
np.inf

inf

In [228]:
array_1 = np.array(
    [
        [4, 1],
        [2, 5]
    ]
)

array_2 = np.array(
    [
        [0, 1],
        [2, 4]
    ]
)

In [237]:
op = array_1 * array_2

array([[ 0,  1],
       [ 4, 20]])

In [236]:
np.isinf(op).all()

np.False_

In [238]:
np.e

2.718281828459045

In [239]:
np.pi

3.141592653589793

### Array Generate

In [248]:
np.arange(0, 11, 1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [256]:
ls = np.linspace(1, 10, 20)
ls

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [257]:
np.round(ls, 2)

array([ 1.  ,  1.47,  1.95,  2.42,  2.89,  3.37,  3.84,  4.32,  4.79,
        5.26,  5.74,  6.21,  6.68,  7.16,  7.63,  8.11,  8.58,  9.05,
        9.53, 10.  ])

In [253]:
np.zeros((2, 2))

array([[0., 0.],
       [0., 0.]])

In [258]:
np.ones((4, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [264]:
# list_ = list()
# list_.append(1)
# list_

em_ = np.empty((4, 4, 3))